version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
    depends_on:
  
volumes:
  pgdata: {}
    