# Utiliser une image de base Python légère
FROM python:3.6-slim-buster

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier requirements.txt dans le conteneur
COPY requirements.txt requirements.txt

RUN apt update -y & apt upgrade -y
# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste de l'application dans le conteneur, y compris data.csv
COPY . .

# Exposer le port sur lequel l'application sera disponible
EXPOSE 5585

# Définir le point d'entrée du conteneur
ENTRYPOINT ["python"]

# Définir la commande par défaut pour exécuter l'application
CMD ["app.py"]


# WORKDIR /app

# COPY requirements.txt ./


# COPY . .

# EXPOSE 4000

# CMD [ "flask", "run", "--host=0.0.0.0", "--port=4000"]