FROM python:3.6-slim-buster

RUN apk add --no-cache python3-dev \
    && pip3 install --upgrade pip

WORKDIR /app
COPY . /app
# RUN pip3 --no-cache-dir install -r requirements.txt
RUN pip install -r requirements.txt

EXPOSE 4585

ENTRYPOINT ["python3"]
CMD ["app.py"]

# WORKDIR /app

# COPY requirements.txt ./


# COPY . .

# EXPOSE 4000

# CMD [ "flask", "run", "--host=0.0.0.0", "--port=4000"]